package com.project.exceptiondemo;

public class Demo {
	public static void main(String[] args) {
		
		try {
			int data=4/2;
			System.out.println(data);
		}
		catch(ArithmeticException e) {
			System.out.println("invalid data,,,,,,,,,,,,,,,,,,");
		}
		System.out.println("next line data,,,,,,,,,,,");
		System.out.println("dgsdfgfdsgfdsg");
		System.out.println("sgfhgthtyhyturtsr");
		System.out.println("fsgjfgfkgtfdksk");
	}

}
